mutation updateListing($listingUUID: String, $updateData: ListingInput) {
  updateListing(listingUUID: $listingUUID, updateData: $updateData) {
    listingType
    listingPurpose
    listingKind
    listingKindCode
    listingSubgroup
  }
}
