mutation updateListing($listingUUID: String, $updateData: ListingInput) {
  updateListing(listingUUID: $listingUUID, updateData: $updateData) {
    guestCapacity
    noOfBedrooms
    noOfBathrooms
  }
}
