mutation addOrUpdateAmenityCategory(
  $categoryData: ListingAmenityCategoryInput
) {
  addOrUpdateAmenityCategory(categoryData: $categoryData) {
    id
    uuid
    title
    description
    amenities {
      title
    }
    createdAt
    updatedAt
  }
}
