mutation addOrUpdateAmenity($amenityData: ListingAmenityInput) {
  addOrUpdateAmenity(amenityData: $amenityData) {
    id
    uuid
    title
    description
    faIcon
    mdiIcon
    category {
      id
      title
    }
  }
}
